# This workflow demonstrates how to use the Cloud Storage connector.
# The workflow creates a Cloud Storage bucket and then deletes it.
# Expected successful output: "SUCCESS"

- init:
    assign:
    - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
    - bucket_name: "glenns-dummy-bucket"
    - existing_bucket: "qbank-test-bucket"
- create_bucket:
    call: googleapis.storage.v1.buckets.insert
    args:
      project: ${project_id}
      body:
        name: ${bucket_name}
- get_bucket:
    call: googleapis.storage.v1.buckets.get
    args:
      bucket: ${bucket_name}
- list_bucket:
    call: googleapis.storage.v1.objects.list
    args:
      bucket: ${existing_bucket}
    result: listResult
- delete_bucket:
    call: googleapis.storage.v1.buckets.delete
    args:
      bucket: ${bucket_name}
- the_end:
    return: ${listResult}
